name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: darrylwest/ubuntu24-gpp1420:latest
    
    strategy:
      matrix:
        build_type: [Release ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y \
          cmake \
          ninja-build \
          git
        
        # Verify installation
        gcc --version
        g++ --version
        cmake --version

    - name: Install Catch2
      run: |
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        git checkout v3.7.1
        cmake -B build -S . -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=/usr/local
        cmake --build build --parallel $(nproc)
        cmake --build build --target install
        cd ..

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_CXX_STANDARD=23 \
          -DENABLE_TESTS=ON \
          -G Ninja

    - name: Build
      run: |
        cmake --build build --parallel $(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --parallel $(nproc)

    - name: Run examples
      run: |
        ./build/examples/txkey -v
        ./build/examples/rtkey
        ./build/examples/rand-base62-key
        ./build/examples/decode_txkey 816xemoY3B8L

    - name: Package artifacts
      run: |
        mkdir -p artifacts/lib artifacts/include artifacts/bin
        cp build/libdomainkeys.a artifacts/lib/
        cp -r include/* artifacts/include/
        cp build/examples/* artifacts/bin/ 2>/dev/null || true
        tar -czf domain-keys-ubuntu-24.10-release.tar.gz artifacts/
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.build_type == 'Release'
      with:
        name: domain-keys-ubuntu-24.10-release
        path: domain-keys-ubuntu-24.10-release.tar.gz
        retention-days: 30
